# Generated by Django 5.2 on 2025-06-03 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_participaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participaciones',
            name='campana_id',
        ),
        migrations.AddField(
            model_name='participaciones',
            name='campana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.campanas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
