# Generated by Django 5.2 on 2025-06-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comunidades_campanas_comunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanas',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='api.comunidades'),
        ),
    ]
