# Generated by Django 5.2 on 2025-06-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_campanas_comunidad'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comunidades',
            table='Comunidad',
        ),
    ]
