# Generated by Django 5.2 on 2025-06-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_comunidades_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comunidades',
            table='Comunidades',
        ),
    ]
