# Generated by Django 5.2 on 2025-06-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comunidades_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comunidades',
            table=None,
        ),
    ]
